[project]
name = "rq3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flair>=0.15.1",
    "llama-index>=0.12.34",
    "nltk>=3.9.1",
]
