[project]
name = "rq1"
version = "0.1.0"
description = "AF"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.2.1",
    "protobuf>=6.30.1",
    "pydantic>=2.10.6",
    "scikit-learn>=1.6.1",
    "sentencepiece>=0.2.0",
    "torch>=2.6.0",
    "transformers>=4.50.0",
]
