[project]
name = "rq2-rebel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.12.31",
    "torch>=2.6.0",
    "transformers>=4.51.3",
]
